### ISSUE TITLE
Server-Code for Hall of Fame

### ISSUE THREAD

**Issue by hoehnp** [Xenoage/Bolzplatz2006#6]
Is the hall of fame still functional? I cannot submit any results from the Allstars League.

**Comment by Xenoage** [comment]
No it isn't, and there are currently no plans to reactivate it from our side.
Consider the website as an archive.

Would you like to have the server-side sources?

**Comment by hoehnp** [comment]
If you would be willing to also release it, it would be nice. At this point I am not sure about hosting yet, but could be nice in future to measure the current user base.

**Comment by Xenoage** [comment]
The sources of the website were not released under the GPL back then. I'll ask the author if he is willing to release it under GPL too.

**Comment by hoehnp** [comment]
for a web code he could also choose AGPL, just as an option.

**Comment by Xenoage** [comment]
The [website](https://github.com/Xenoage/Bolzplatz2006/tree/master/website) was now uploaded.
